server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  # Allow range requests for video/audio
  location ~* \.(?:mp4|mp3|ogg|webm)$ {
    add_header Accept-Ranges bytes;
  }
}
